initial commit
alinaoers/mipt_2 pull request #1
Opened 2020-04-09 21:32 UTC by alinaoers

2020-04-15 11:05 UTC, alexmikhalevich requested changes
В целом хорошо. Нужно только удалить ненужные файлы из репо и прокомментировать либо исправить замечание ниже.

2020-04-15 11:05 UTC, maked0n commented on BIG_PATTERN/include/Army.hpp
> +    int size_catap_ = 50;
а зачем эти поля делать публичными? и ниже везде аналогично

2020-04-20 19:36 UTC, alinaoers commented on BIG_PATTERN/include/Army.hpp
> +    int size_catap_ = 50;
Здравствуйте, насчет количества воинов - size_catap_ и size_cross_ -  их сделаю приватными, а векторы из этих воинов мне нужны публичные, чтобы изменять их во время самой игры и при создании армии

2020-04-20 20:49 UTC, maked0n commented on BIG_PATTERN/include/Army.hpp
> +    int size_catap_ = 50;
тогда можно создать соответствующие геттеры и сеттеры, а поле сделать приватным

2020-04-25 11:16 UTC, alexmikhalevich approved these changes

2021-04-02 22:03 UTC, merged